#!/bin/bash

# set DOCKER_USER to a organization for the images

# import global functions
source $(dirname $(readlink -f $0))/_functions.sh

# base
deprecated "base:precise" "builder/base/" "Dockerfile-precise"
deprecated "base:trusty" "builder/base/" "Dockerfile-trusty"

# base-core
build "base-core:20150219" "builder/base-core/"

# base-java
build "base-java:20150219" "builder/base-java/"

# gcc
build "gcc:4.6" "builder/gcc/gcc_4.6/"
build "gcc:4.7" "builder/gcc/gcc_4.7/"
build "gcc:4.8" "builder/gcc/gcc_4.8/"

# scala
build "scala:2.9.3" "builder/scala/scala_2.9.3/"
build "scala:2.10.4" "builder/scala/scala_2.10.4/"
build "scala:2.11.5" "builder/scala/scala_2.11.5/"

# clojure
build "leiningen:2.5.1" "builder/clojure/leiningen_2.5.1/"

# nodejs
build "nodejs:0.8.26" "builder/nodejs/nodejs_0.8.26/"
build "nodejs:0.10.36" "builder/nodejs/nodejs_0.10.36/"
build "nodejs:0.11.14" "builder/nodejs/nodejs_0.11.14/"

# golang
build "golang:1.2.2" "builder/golang/golang_1.2.2/"
build "golang:1.3.3" "builder/golang/golang_1.3.3/"
build "golang:1.4.1" "builder/golang/golang_1.4.1/"
build "golang:1.4.2" "builder/golang/golang_1.4.2/"

# python
build "python:2.7.9" "builder/python/python_2.7.9/"
build "python:3.2.6" "builder/python/python_3.2.6/"
build "python:3.3.6" "builder/python/python_3.3.6/"
build "python:3.4.2" "builder/python/python_3.4.2/"

# ruby
build "ruby:1.9.3-p551" "builder/ruby/ruby_1.9.3-p551/"
build "ruby:2.0.0-p598" "builder/ruby/ruby_2.0.0-p598/"
build "ruby:2.1.5" "builder/ruby/ruby_2.1.5/"
build "ruby:2.2.0" "builder/ruby/ruby_2.2.0/"

# groovy + grails
build "grails:2.3.5" "builder/grails/grails_2.3.5/"

# elasticsearch
build "elasticsearch:0.90.13" "database/elasticsearch/elasticsearch_0.90.13/"
build "elasticsearch:1.0.3" "database/elasticsearch/elasticsearch_1.0.3/"
build "elasticsearch:1.1.2" "database/elasticsearch/elasticsearch_1.1.2/"
build "elasticsearch:1.2.3" "database/elasticsearch/elasticsearch_1.2.3/"
build "elasticsearch:1.3.8" "database/elasticsearch/elasticsearch_1.3.8/"
build "elasticsearch:1.4.3" "database/elasticsearch/elasticsearch_1.4.3/"

# cassandra
build "cassandra:2.0.12" "database/cassandra/cassandra_2.0.12/"
build "cassandra:2.1.3" "database/cassandra/cassandra_2.1.3/"

# mongodb
build "mongodb:2.2.7" "database/mongodb/mongodb_2.2.7/"
build "mongodb:2.4.12" "database/mongodb/mongodb_2.4.12/"
build "mongodb:2.6.7" "database/mongodb/mongodb_2.6.7/"
build "mongodb:2.6.8" "database/mongodb/mongodb_2.6.8/"
build "mongodb:3.0.0" "database/mongodb/mongodb_3.0.0/"
