#!/bin/bash

# set DOCKER_USER to an organization for the images

# import global functions
source $(dirname $(readlink -f $0))/_functions.sh

# base
skip "base:precise"
remove "base:trusty"

# gcc
remove "gcc:4.6"
remove "gcc:4.7"
remove "gcc:4.8"

# scala
remove "scala:2.9.3"
remove "scala:2.10.4"
remove "scala:2.11.5"

# clojure
remove "leiningen:2.5.1"

# nodejs
remove "nodejs:0.8.26"
remove "nodejs:0.10.36"
remove "nodejs:0.11.14"

# golang
remove "golang:1.2.2"
remove "golang:1.3.3"
remove "golang:1.4.1"

# python
remove "python:2.7.9"
remove "python:3.2.6"
remove "python:3.3.6"
remove "python:3.4.2"

# elasticsearch
remove "elasticsearch:0.90.13"
remove "elasticsearch:1.0.3"
remove "elasticsearch:1.1.2"
remove "elasticsearch:1.2.3"
remove "elasticsearch:1.3.8"
remove "elasticsearch:1.4.3"
