#!/bin/bash

# set DOCKER_USER to an organization for the images

# import global functions
source $(cd $(dirname $(dirname $0)) && pwd)/_functions.sh

# base
remove "base:precise"
remove "base:trusty"

# base-core
remove "base-core:20150918"

# base-java
remove "base-java:20150918"

# ansible
remove "ansible:1.9.2"

# gcc
remove "gcc:4.6"
remove "gcc:4.7"
remove "gcc:4.8"

# scala
remove "scala:2.9.3"
remove "scala:2.10.4"
remove "scala:2.10.5"
remove "scala:2.11.5"
remove "scala:2.11.6"

# clojure
remove "leiningen:2.5.1"

# nodejs
remove "nodejs:0.8.26"
remove "nodejs:0.10.36"
remove "nodejs:0.11.14"
remove "nodejs:0.12.0"

# golang
remove "golang:1.2.2"
remove "golang:1.3.3"
remove "golang:1.4.1"
remove "golang:1.4.2"
remove "golang:1.5.1"

# python
remove "python:2.7.9"
remove "python:3.2.6"
remove "python:3.3.6"
remove "python:3.4.2"

# ruby
remove "ruby:1.9.3-p551"
remove "ruby:2.0.0-p598"
remove "ruby:2.1.5"
remove "ruby:2.2.0"

# groovy + grails
remove "grails:2.3.5"
remove "grails:2.4.5"

# elasticsearch
remove "elasticsearch:0.90.13"
remove "elasticsearch:1.0.3"
remove "elasticsearch:1.1.2"
remove "elasticsearch:1.2.3"
remove "elasticsearch:1.3.8"
remove "elasticsearch:1.4.3"
remove "elasticsearch:1.6.2"
remove "elasticsearch:1.7.1"

# cassandra
remove "cassandra:2.0.12"
remove "cassandra:2.1.3"
remove "cassandra:2.1.8"
remove "cassandra:2.1.9"
remove "cassandra:2.2.0"
remove "cassandra:2.2.1"

# mongodb
remove "mongodb:2.2.7"
remove "mongodb:2.4.12"
remove "mongodb:2.6.7"
remove "mongodb:2.6.8"
remove "mongodb:2.6.11"
remove "mongodb:3.0.0"
remove "mongodb:3.0.6"

