#!/bin/bash

# set DOCKER_USER to an organization for the images

# import global functions
source $(dirname $(readlink -f $0))/_functions.sh

# base
publish "base:precise"
publish "base:trusty"

# gcc
publish "gcc:4.6"
publish "gcc:4.7"
publish "gcc:4.8"

# scala
publish "scala:2.9.3"
publish "scala:2.10.4"
publish "scala:2.11.5"

# clojure
publish "leiningen:2.5.1"

# nodejs
publish "nodejs:0.8.26"
publish "nodejs:0.10.36"
publish "nodejs:0.11.14"

# golang
publish "golang:1.2.2"
publish "golang:1.3.3"
publish "golang:1.4.1"

# python
publish "python:2.7.9"
publish "python:3.2.6"
publish "python:3.3.6"
publish "python:3.4.2"

# elasticsearch
publish "elasticsearch:0.90.13"
publish "elasticsearch:1.0.3"
publish "elasticsearch:1.1.2"
publish "elasticsearch:1.2.3"
publish "elasticsearch:1.3.8"
publish "elasticsearch:1.4.3"

# mongodb
publish "mongodb:2.2.7"
publish "mongodb:2.4.12"
publish "mongodb:2.6.7"
