FROM sphonic/base-java:20150219

MAINTAINER Daniel Malon <operations@sphonic.com>

ADD https://raw.githubusercontent.com/technomancy/leiningen/2.5.1/bin/lein /usr/local/bin/lein

RUN \
  chmod +x /usr/local/bin/lein
